language: node_js
sudo: false
node_js:
  - '6.9.4'
env:
  - NODE_ENV=test
cache:
  yarn: true
  directories:
    - node_modules
before-script:
  - yarn global add codecov
  - yarn
script:
  - yarn run test:ci
  - codecov
