language: node_js
sudo: false
node_js:
  - '6.9.5'
env:
  - NODE_ENV=test
cache:
  yarn: true
  directories:
    - $HOME/.npm
    - $HOME/.yarn-cache
before_script:
  - yarn global add codecov
script:
  - yarn run test:ci
  - codecov
