version: '2'

services:
  web:
    build:
      context: .
      args:
        - NODE_ENV=development
    environment:
      - NODE_ENV=development
    ports:
      - 3000
    volumes:
      - ./src:/usr/src/skipass/src:rw
    command: pm2-dev start ecosystem.config.js

  proxy:
    build: nginx
    ports:
      - 8888:80
      - 4444:443
    depends_on:
      - web
    volumes:
      - ./nginx/config/nginx.development.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/dev-certs:/etc/letsencrypt/live/skipass.site:ro
    volumes_from:
      - web:ro
