version: '2'

services:
  web:
    build: .
    environment:
      - NODE_ENV=production
    ports:
      - 3000

  proxy:
    image: blobor/skipass-nginx-proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
