version: '2'

services:
  web:
    build: .
    environment:
      - NODE_ENV=development
    ports:
      - 3000
    volumes:
      - ./:/usr/src/skipass

  proxy:
    build: nginx
    ports:
      - 80:80
      - 443:443
    depends_on:
      - web
    volumes:
      - ./nginx/config/nginx.development.conf:/etc/nginx/nginx.conf
      - ./nginx/dev-certs:/etc/letsencrypt/live/skipass.site
