version: '2'

services:
  web:
    image: blobor/skipass-web-api:0.40.0
    environment:
      - NODE_ENV=production
      - GOOGLE_TRACKING_ID
    ports:
      - 3000

  proxy:
    image: blobor/skipass-nginx-proxy:0.40.1
    ports:
      - 80:80
      - 443:443
    depends_on:
      - web
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
    volumes_from:
      - web:ro
