version: '2'

services:
  web:
    build: .
    environment:
      - NODE_ENV=development
    ports:
      - 3000

  proxy:
    build: nginx
    ports:
      - 8080:80
      - 4433:433
    volumes:
      - ./nginx/dev-certs:/etc/letsencrypt/live/skipass.site
