export const TOGGLE_DEVELOPER_MODE = Symbol('TOGGLE_DEVELOPER_MODE')

export const CHANGE_SEARCH_SKIPASS_NUMBER = Symbol('CHANGE_SEARCH_CARD_NUMBER')

export const FETCH_SKIPASS_REQUEST = Symbol('FETCH_SKIPASS_REQUEST')
export const FETCH_SKIPASS_SUCCESS = Symbol('FETCH_SKIPASS_SUCCESS')
export const FETCH_SKIPASS_FAILURE = Symbol('FETCH_SKIPASS_FAILURE')

export const TOGGLE_SKIPASS_CAN_BE_ADDED = Symbol('TOGGLE_SKIPASS_CAN_BE_ADDED')

export const STORE_SKIPASS_REQUEST = Symbol('STORE_SKIPASS_REQUEST')
export const STORE_SKIPASS_SUCCESS = Symbol('STORE_SKIPASS_SUCCESS')
export const STORE_SKIPASS_FAILURE = Symbol('STORE_SKIPASS_FAILURE')

export const FETCH_STORED_SKIPASSES_REQUEST = Symbol('FETCH_STORED_SKIPASSES_REQUEST')
export const FETCH_STORED_SKIPASSES_SUCCESS = Symbol('FETCH_STORED_SKIPASSES_SUCCESS')
export const FETCH_STORED_SKIPASSES_FAILURE = Symbol('FETCH_STORED_SKIPASSES_FAILURE')

export const REMOVE_STORED_SKIPASS_REQUEST = Symbol('REMOVE_STORED_SKIPASS_REQUEST')
export const REMOVE_STORED_SKIPASS_SUCCESS = Symbol('REMOVE_STORED_SKIPASS_SUCCESS')
export const REMOVE_STORED_SKIPASS_FAILURE = Symbol('REMOVE_STORED_SKIPASS_FAILURE')
