export const CHANGE_SEARCH_SKIPASS_NUMBER = 'CHANGE_SEARCH_CARD_NUMBER'

export const FETCH_SKIPASS_REQUEST = 'FETCH_SKIPASS_REQUEST'
export const FETCH_SKIPASS_SUCCESS = 'FETCH_SKIPASS_SUCCESS'
export const FETCH_SKIPASS_FAILURE = 'FETCH_SKIPASS_FAILURE'

export const CLOSE_NAVIGATION_DRAWER = 'CLOSE_NAVIGATION_DRAWER'
export const TOGGLE_NAVIGATION_DRAWER = 'TOGGLE_NAVIGATION_DRAWER'

export const TOGGLE_SKIPASS_CAN_BE_ADDED = 'TOGGLE_SKIPASS_CAN_BE_ADDED'
