export const CHANGE_SEARCH_SKIPASS_NUMBER = 'CHANGE_SEARCH_CARD_NUMBER'
export const FETCH_SKIPASS_REQUEST = 'FETCH_SKIPASS_REQUEST'
export const FETCH_SKIPASS_SUCCESS = 'FETCH_SKIPASS_SUCCESS'
export const FETCH_SKIPASS_FAILURE = 'FETCH_SKIPASS_FAILURE'
