export const CHANGE_SEARCH_SKIPASS_NUMBER = 'CHANGE_SEARCH_CARD_NUMBER'

export const FETCH_SKIPASS_REQUEST = 'FETCH_SKIPASS_REQUEST'
export const FETCH_SKIPASS_SUCCESS = 'FETCH_SKIPASS_SUCCESS'
export const FETCH_SKIPASS_FAILURE = 'FETCH_SKIPASS_FAILURE'

export const TOGGLE_SKIPASS_CAN_BE_ADDED = 'TOGGLE_SKIPASS_CAN_BE_ADDED'

export const STORE_SKIPASS_REQUEST = 'STORE_SKIPASS_REQUEST'
export const STORE_SKIPASS_SUCCESS = 'STORE_SKIPASS_SUCCESS'
export const STORE_SKIPASS_FAILURE = 'STORE_SKIPASS_FAILURE'

export const FETCH_STORED_SKIPASSES_REQUEST = 'FETCH_STORED_SKIPASSES_REQUEST'
export const FETCH_STORED_SKIPASSES_SUCCESS = 'FETCH_STORED_SKIPASSES_SUCCESS'
export const FETCH_STORED_SKIPASSES_FAILURE = 'FETCH_STORED_SKIPASSES_FAILURE'

export const REMOVE_STORED_SKIPASS_REQUEST = 'REMOVE_STORED_SKIPASS_REQUEST'
export const REMOVE_STORED_SKIPASS_SUCCESS = 'REMOVE_STORED_SKIPASS_SUCCESS'
export const REMOVE_STORED_SKIPASS_FAILURE = 'REMOVE_STORED_SKIPASS_FAILURE'
